import Head from 'next/head'
import PageLayerOne from '../Components/PageLayerOne'
import PageLayerTwo from '../Components/PageLayerTwo'

// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='relative h-fit w-full'>
      <Head>
        <title>{'Arhyel\'s Portfolio'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* First Layer */}
      <PageLayerOne/>
      

      {/* Second Layer */}
      {/* <PageLayerTwo/> */}
    </div>
  )
}
