import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* First Layer */}
      
      <div className={styles.firstLayer}>
          <h1 className='text-white'>THIS IS THE FIRST LAYER</h1>
      </div>

      {/* Second Layer */}
      
      <div className={styles.secondLayer}>
          <h1>THIS IS THE SECOND LAYER</h1>
      </div>
    </div>
  )
}
